#!/bin/bash

python to_theme.py info.php theme/info.php
python to_theme.py works.php theme/works.php
python to_theme.py index.php theme/content.php

python to_theme.py header.php theme/header.php
python to_theme.py footer.php theme/footer.php
python to_theme.py const.php theme/const.php


python to_theme.py style.css theme/style.css
yuicompressor theme/style.css > theme/style.min.css

python to_theme.py js/main.js theme/js/main.js
touch theme/js/main.min.js
yuicompressor theme/js/main.js > theme/js/main.min.js

rm -rf theme/img
cp -r img theme/img

rm -rf theme/css
cp -r css theme/css

rm -rf theme/js
cp -r js theme/js

rm theme.zip
zip -r theme.zip theme

git add .
git commit -m "theme build"
